const REPORT_STATUS_CODE_MAPPING = {
  RTD: "RTO-RTD",
  RTO: "RTO",
  DL: "DELIVERED",
  OO: "OUT FOR DELIVERY",
  OT: "TRANSIT",
  PP: "PICKED",
  OC: "CANCELLED",
  OM: "MANIFESTED",
  OP: "PLACED",
  NDR: "UNDELIVERED",
};

const REPORT_STATUS_TYPE_MAPPING = {
  RTD: "RTD",
  RTO: "RTO",
  DL: "DELIVERED",
  OO: "OUT FOR DELIVERY",
  OT: "IN TRANSIT",
  PP: "PICKED",
  OC: "CANCELLED",
  OM: "MANIFESTED",
  OP: "PLACED",
  NDR: "UNDELIVERED",
};

module.exports = {
  REPORT_STATUS_CODE_MAPPING,
  REPORT_STATUS_TYPE_MAPPING,
};
