// obj = {
//   breadth: 10,
//   is_cod: false,
//   weight: 0.5,
//   item_tax_percentage: "0",
//   web_address: null,
//   billing_zone: "D",
//   dispatch_mode: "Express",
//   client_order_id: "3995345",
//   logo: null,
//   pickrr_order_id: "28652712",
//   sku: "APPLEIPHONEXR2487",
//   item_list: [
//     {
//       sku: "APPLEIPHONEXR2487",
//       item_tax_percentage: 0,
//       item_height: null,
//       name: null,
//       item_name: "Pearl Bush Marble iPhone XR Back Cover",
//       price: 177,
//       item_weight: null,
//       hsn: null,
//       shipping_charge: null,
//       tax_per: 0,
//       variant_title: null,
//       quantity: 4,
//       item_breadth: null,
//       item_length: null,
//     },
//   ],
//   user_id: null,
//   order_type: "Express",
//   hsn_code: null,
//   company_name: "XYZ",
//   product_name: "Pearl Bush Marble iPhone XR Back Cover",
//   status: {
//     current_status_time: datetime(2021, 11, 29, 5, 16),
//     current_status_type: "OT",
//     received_by: null,
//     current_status_body: "Shipment delivered 999  Delivered",
//     current_status_location: "KOZHIKODE",
//     current_status_val: null,
//   },
//   info: {
//     from_state: "GUJARAT",
//     invoice_value: 336,
//     from_name: "zapvi zapvi helpzapviin",
//     to_address: "PADANNA VALAPPU, PAYYANAKKAL  KOZHIKODE  KL IN",
//     to_state: "KERALA",
//     courier_name: "ecomm_new",
//     to_pincode: "673003",
//     to_address_id: 28463676,
//     to_email: "muhammedshahid004@gmail.com",
//     from_email: "help@zapvi.in",
//     to_city: "CALICUT",
//     source_address_id: 396904,
//     to_name: "kunal bariwal",
//     from_phone_number: "+916351212822",
//     from_city: "SURAT",
//     user_id: null,
//     cod_amount: 0,
//     is_open_ndr: false,
//     to_phone_number: "+919101254133",
//     from_pincode: "395010",
//     from_address: "23 4th Floor Girivar Park Saniya hemad Gam surat",
//   },
//   is_reverse: false,
//   courier_used: "ecomm_new",
//   courier_tracking_id: "12346",
//   height: 3,
//   courier_parent_name: "Ecom Express",
//   client_extra_var: null,
//   err: null,
//   ops_profile: "rahul.sharma@pickrr.com",
//   track_arr: [
//     {
//       scan_type: "DD",
//       scan_datetime: datetime(2021, 9, 29, 5, 16),
//       scan_location: "KOZHIKODE",
//       scan_status: "Shipment delivered 999  Delivered",
//       pickrr_sub_status_code: "",
//       courier_status_code: "999",
//     },
//     {
//       scan_type: "OO",
//       scan_datetime: datetime(2021, 9, 29, 2, 55),
//       scan_location: "KOZHIKODE",
//       scan_status: "Shipment out for delivery, assigned to EmployeeNIYAZA ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "006",
//     },
//     {
//       scan_type: "RAD",
//       scan_datetime: datetime(2021, 9, 29, 1, 40),
//       scan_location: "KOZHIKODE",
//       scan_status: "Shipment in-scan at DC ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "005",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 29, 1, 1),
//       scan_location: "KOZHIKODE",
//       scan_status: "Bag scanned at DC ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 28, 12, 42),
//       scan_location: "WALEYAR HUB",
//       scan_status: "In-Transit ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 28, 12, 40),
//       scan_location: "WALEYAR HUB",
//       scan_status: "Bag connected from HUB ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 28, 8, 55),
//       scan_location: "WALEYAR HUB",
//       scan_status: "Shipment connected from HUB (Bag No. SE12246176) ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "RAD",
//       scan_datetime: datetime(2021, 9, 28, 8, 14),
//       scan_location: "WALEYAR HUB",
//       scan_status: "Shipment in-scan at HUB ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "005",
//     },
//     {
//       scan_type: "RAD",
//       scan_datetime: datetime(2021, 9, 28, 8, 14),
//       scan_location: "WALEYAR HUB",
//       scan_status: "Shipment in-scan at HUB ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "005",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 28, 8, 8),
//       scan_location: "WALEYAR HUB",
//       scan_status: "Bag scanned at Hub ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 27, 18, 30),
//       scan_location: "BENGALURU",
//       scan_status: "In-Transit ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 27, 11, 26),
//       scan_location: "BENGALURU",
//       scan_status: "Bag scanned at Hub ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 26, 1, 57),
//       scan_location: "SURAT",
//       scan_status: "In-Transit ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 25, 21, 34),
//       scan_location: "SURAT",
//       scan_status: "Bag scanned at Hub ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "SHP",
//       scan_datetime: datetime(2021, 9, 25, 17, 30),
//       scan_location: "SURAT",
//       scan_status: "Shipment in-scan ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "002",
//     },
//     {
//       scan_type: "OT",
//       scan_datetime: datetime(2021, 9, 25, 17, 30),
//       scan_location: "SURAT",
//       scan_status: "Shipment connected to WALEYAR HUB - WLH (Bag No. PL24791439) ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "003",
//     },
//     {
//       scan_type: "SHP",
//       scan_datetime: datetime(2021, 9, 25, 16, 31),
//       scan_location: "SURAT",
//       scan_status: "Shipment in-scan ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "002",
//     },
//     {
//       scan_type: "PP",
//       scan_datetime: datetime(2021, 9, 25, 7, 6),
//       scan_location: "SURAT",
//       scan_status: "Shipment Picked Up ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "0011",
//     },
//     {
//       scan_type: "OFP",
//       scan_datetime: datetime(2021, 9, 25, 6, 16),
//       scan_location: "SURAT",
//       scan_status: "Out for Pickup ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "1230",
//     },
//     {
//       scan_type: "OM",
//       scan_datetime: datetime(2021, 9, 25, 4, 45),
//       scan_location: "SURAT",
//       scan_status: "Pickup Assigned ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "1220",
//     },
//     {
//       scan_type: "PPF",
//       scan_datetime: datetime(2021, 9, 24, 7, 15),
//       scan_location: "SURAT",
//       scan_status: "Pickup Failed, Shipment Not Handed Over ",
//       pickrr_sub_status_code: "SNR",
//       courier_status_code: "1340",
//     },
//     {
//       scan_type: "OFP",
//       scan_datetime: datetime(2021, 9, 24, 6, 18),
//       scan_location: "SURAT",
//       scan_status: "Out for Pickup ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "1230",
//     },
//     {
//       scan_type: "OM",
//       scan_datetime: datetime(2021, 9, 24, 4, 52),
//       scan_location: "SURAT",
//       scan_status: "Pickup Assigned ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "1220",
//     },
//     {
//       scan_type: "OP",
//       scan_datetime: datetime(2021, 9, 23, 10, 38),
//       scan_location: "SURAT",
//       scan_status: "Soft data uploaded ",
//       pickrr_sub_status_code: "",
//       courier_status_code: "001",
//     },
//   ],
//   length: 15,
//   edd_stamp: datetime(2021, 12, 28, 18, 37, 9, 158000),
//   quantity: 2,
//   tracking_id: "12346",
//   auth_token: "5eaacc0e92a1e8f5ff9b75a577a6ea7a125971",
//   order_created_at: datetime(2021, 9, 23, 10, 38, 2),
//   user_pk: null,
//   created_at: datetime(2021, 10, 28, 18, 37, 9, 158000),
//   updated_at: datetime(2021, 10, 28, 18, 37, 9, 158000),
//   courier_input_weight: 0.49,
//   last_update_from: "backfill",
//   user_email: "ruhan@pickrr.com",
//   website: null,
//   status_pk: 1243,
//   notification_user: {
//     email: "ruhan@pickrr.com",
//     coins_to_rupee: 1.0,
//     delay_delivery_in_days: 1,
//     delivery_delay: ["wp"],
//     email_coins: 0,
//     free_email: -1,
//     free_sms: 2,
//     free_sms_events: ["order_placed", "picked_up_delayed"],
//     free_wp: 1,
//     free_wp_events: ["order_placed"],
//     is_active: true,
//     kwargs: {},
//     order_cancelled: ["wp"],
//     order_delivered: ["wp"],
//     order_in_transit: ["wp"],
//     order_not_delivered: ["wp"],
//     order_picked_up: ["wp"],
//     order_placed: ["wp"],
//     out_for_delivery_er: ["wp"],
//     out_for_delivery_sd: ["wp"],
//     picked_up_delayed: ["wp"],
//     sms_coins: 0.15,
//     total_coins: 5398064.55,
//     wp_coins: 100.0,
//   },
// };
