const trackingObj = {
  _id: "61cba1d8d00dd38fc923c6f0",
  breadth: 10,
  is_cod: false,
  weight: 0.5,
  item_tax_percentage: "0",
  billing_zone: "D",
  dispatch_mode: "Express",
  client_order_id: "3709997",
  pickrr_order_id: "36574558",
  sku: "DWOW0034BB1",
  item_list: [
    {
      sku: "DWOW0034BB1",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Apple Cider Vinegar Shampoo",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DMCA0117AB21",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Naked & Raw Coffee Scalp & Hair Oil For Hair Growth With Redensyl & Argan Oil",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "SMYMUDGREEN2020",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Utility Pouch-Mud Green",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DWOW0030AB1",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Apple Cider Vinegar Face Wash",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DWOW0138BB1",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Red Onion Shampoo",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DWOW0103BB1",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Onion Black Seed Hair Oil",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DMCA0116AB21",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Naked & Raw Coffee Shampoo For Hair Fall Control With Protein & Argan Oil",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
    {
      sku: "DVLC0244AB14",
      item_tax_percentage: "0",
      item_height: null,
      name: null,
      item_name: "Neem Face Wash With Chamomile & Tea Tree",
      price: null,
      item_weight: null,
      hsn: null,
      shipping_charge: null,
      tax_per: "0",
      variant_title: null,
      quantity: 1,
      item_breadth: null,
      item_length: null,
    },
  ],
  user_id: "175485",
  order_type: "Express",
  hsn_code: null,
  company_name: "OCTAVOS ENTERPRISE SOLUTIONS PRIVATE LIMITED",
  product_name: "Apple Cider Vinegar Shampoo",
  status: {
    current_status_time: "2021-12-30T11:49:28.994Z",
    current_status_type: "DL",
    received_by: "",
    current_status_body: "Air-restricted product. Move by surface",
    current_status_location: "Ahmedabad_AslaliRoad_GW (Gujarat)",
    current_status_val: null,
    courier_status_code: "S-MAR_UD",
    pickrr_sub_status_code: "",
  },
  info: {
    from_state: "GUJARAT",
    invoice_value: 199,
    from_name: "smytten warehouse",
    to_address:
      "Nishiganj nisimoye high scool  opposite of tvs show room Nishiganj Nihimoye High School",
    to_state: "WEST BENGAL",
    courier_name: "delhivery",
    to_pincode: "736157",
    to_address_id: 36400252,
    to_email: null,
    from_email: null,
    to_city: "COOCH BEHAR",
    source_address_id: 539003,
    to_name: "gargi roy",
    from_phone_number: "8657698836",
    from_city: "AHMEDABAD",
    user_id: "175485",
    cod_amount: null,
    is_open_ndr: false,
    to_phone_number: "8514043817",
    from_pincode: "382427",
    from_address:
      "Smytten, M.chandulal estate,1st floor-abbott health care ltdOpp.ashapura hotelNear ekta group of companies ASLALIAhmedabad,Gujarat  ",
  },
  is_reverse: false,
  courier_used: "delhivery",
  courier_tracking_id: "7420143210184",
  height: 10,
  courier_parent_name: "Delhivery",
  client_extra_var: null,
  err: null,
  ops_profile: "gaurav.singh@pickrr.com",
  track_arr: [
    {
      scan_datetime: "2021-12-30T11:10:58.994Z",
      scan_type: "OT",
      scan_status: "Air-restricted product. Move by surface",
      scan_location: "Ahmedabad_AslaliRoad_GW (Gujarat)",
      pickrr_sub_status_code: "",
      courier_status_code: "S-MAR_UD",
      update_source: "kafka",
      update_time: "2021-12-30T11:11:01.339Z",
      system_updated_at: "2021-12-30T11:11:01.339Z",
      pickup_datetime: "2021-12-28T23:46:32.156Z",
    },
    {
      scan_datetime: "2021-12-30T11:09:04.000Z",
      scan_type: "PP",
      scan_status: "Shipment picked up",
      scan_location: "Ahmedabad_AslaliRoad_GW (Gujarat)",
      pickrr_sub_status_code: "",
      courier_status_code: "X-PPOM_UD",
      update_source: "kafka",
      update_time: "2021-12-30T11:11:01.059Z",
      system_updated_at: "2021-12-30T11:11:01.059Z",
      pickup_datetime: "2021-12-28T23:46:32.156Z",
    },
    {
      scan_datetime: "2021-12-28T23:46:32.204Z",
      scan_type: "OM",
      scan_status: "Manifest uploaded",
      scan_location: "HQ (Haryana)",
      pickrr_sub_status_code: "",
      courier_status_code: "X-UCI_UD",
      update_source: "kafka",
      update_time: "2021-12-28T23:46:33.374Z",
      system_updated_at: "2021-12-28T23:46:33.374Z",
      pickup_datetime: "2021-12-28T23:46:32.156Z",
    },
    {
      scan_type: "OP",
      scan_status: "Order Placed",
      scan_datetime: "2021-12-28T23:46:00.000Z",
      scan_location: null,
      pickrr_sub_status_code: "",
      courier_status_code: "",
    },
  ],
  length: 10,
  edd_stamp: "2022-01-06T23:59:00.000Z",
  quantity: "1",
  tracking_id: "7420143210184",
  order_created_at: "2021-12-28T23:46:30.553Z",
  user_pk: "175485",
  created_at: "2021-12-28T23:46:32.595Z",
  updated_at: "2021-12-30T11:11:02.527Z",
  courier_input_weight: 0.5,
  user_email: "chhavi@smytten.com",
  auth_token: "33d8f654722f8959c5f68271730f28de175485",
  website: "Smytten",
  label_logo: null,
  last_update_from: "async",
  ewaybill_number: null,
  is_mps: null,
  rto_waybill: null,
  waybill_type: "MASTER",
  pdd_date: null,
  pickup_address_pk: "539003",
  status_pk: "36570718",
  audit: [],
};

module.exports = {
  trackingObj,
};
