/* eslint-disable require-jsdoc */
const GetTrackingJsonParentKeys = async () => [
  "order_type",
  "client_order_id",
  "courier_tracking_id",
  "courier_used",
  "company_name",
  "web_address",
  "logo",
  "edd_stamp",
  "err",
  "product_name",
  "client_extra_var",
  "length",
  "breadth",
  "height",
  "weight",
  "pickrr_order_id",
  "item_list",
  "billing_zone",
  "dispatch_mode",
  "is_reverse",
  "quantity",
  "hsn_code",
  "item_tax_percentage",
  "courier_parent_name",
  "info",
  "auth_token",
  "track_arr",
  "status",
];
const GetTrackJsonInfokeys = async () => [
  "cod_amount",
  "invoice_value",
  "to_name",
  "to_email",
  "to_address",
  "to_pincode",
  "to_phone_number",
  "to_city",
  "from_city",
  "from_pincode",
  "courier_name",
  "is_open_ndr",
  "to_state",
  "from_state",
  "from_email",
  "from_address",
  "from_name",
  "source_address_id",
  "to_address_id",
  "from_phone_number",
];

const TRACK_ARRAY_OMIT_FIELDS_CLIENT_TRACKING = [
  "scan_datetime",
  "scan_location",
  "scan_status",
  "system_updated_at",
  "update_source",
  "update_time",
  "pickup_datetime",
];

module.exports = {
  GetTrackingJsonParentKeys,
  GetTrackJsonInfokeys,
  TRACK_ARRAY_OMIT_FIELDS_CLIENT_TRACKING,
};
