const cv = {
    'dtdc': 'DTDC',
    'dtdc_air': 'DTDC',
    'dtdc_docs_250': 'DTDC',
    'dtdc_docs_100': 'DTDC',
    'bluedart': 'BLUEDART',
    'bluedart_dart_plus': 'BLUEDART',
    'bluedart_air_zookr': 'BLUEDART',
    'bluedart_dg_zookr': 'BLUEDART',
    'bluedart_ras_ncr': 'BLUEDART',
    'bluedart_ras_external': 'BLUEDART',
    'bluedart_air_yn_mumbai_chen_hyd_bang': 'BLUEDART',
    'fedex': 'FEDEX',
    'fedex_po': 'FEDEX',
    'fedex_economy': 'FEDEX',
    'fedex_so': 'FEDEX',
    'fedex_3kg': 'FEDEX',
    'fedex_3kg_surface': 'FEDEX',
    'india_post': 'INDIA POST',
    'maruti': 'Shree Maruti Courier',
    'firstflight': 'First Flight',
    'professional': 'Professional',
    'delhivery': 'Delhivery',
    'delhivery_express': 'Delhivery',
    'delhivery_non_est': 'Delhivery',
    'overnite': 'Overnite',
    'gojavas': 'GoJavas',
    'aramex': 'Aramex',
    'NECC': 'NECC',
    'dotzot': 'DOTZOT',
    'holisol': 'Holisol',
    'innovex': 'Innovex',
    'velex': 'Velex',
    'bookmypacket': 'BookMyPacket',
    'wedib': 'WeDIB',
    'xpressbees': 'Xpressbees',
    'xpressbees_non_est': 'Xpressbees',
    'delhivery_air': 'Delhivery',
    'ecommexpress': 'Ecom Express',
    'ecommexpress_ras': 'Ecom Express',
    'delhivery_bulk': 'Delhivery',
    'delhivery_air_zookr': 'Delhivery',
    'delhivery_dg_zookr': 'Delhivery',
    'bookmypacket_zookr': 'BookMyPacket',
    'dotzot_zookr': 'DOTZOT',
    'xpressbees_zookr': 'Xpressbees',
    'xpressbees_weshyp': 'Xpressbees',
    'xpressbees_2kg': 'Xpressbees',
    'xpressbees_5kg': 'Xpressbees',
    'xpressbees_10kg': 'Xpressbees',
    'xpressbees_20kg': 'Xpressbees',
    'weshyp_delhivery_air_bulk': 'Delhivery',
    'weshyp_delhivery_air_express': 'Delhivery',
    'weshyp_delhivery_express': 'Delhivery',
    'bmp_surface': 'Bookmypacket',
    'weshyp_xpressbees': 'Xpressbees',
    'delhivery_heavy': 'Delhivery',
    'delhivery_heavy_mps': 'Delhivery',
    'delhivery_bulk_mps': 'Delhivery',
    'delhivery_ncr_mps': 'Delhivery',
    'vulcan_courier': 'Vulcan Courier',
    'ekart': 'Ekart',
    'ekart_new': 'Ekart',
    'ekart_new_non_est': 'Ekart',
    'ekart_new_surface': 'Ekart',
    'ecomm_new': 'Ecom Express',
    'shadowfax': 'ShadowFax',
    'shadowfax_bulk': 'ShadowFax',
    'kerry_docs': 'KerryIndev',
    'delhivery_5kg': 'Delhivery',
    'delhivery_5kg_mps': 'Delhivery',
    'parceldo': 'ParcelDo',
    'parceldo_sdd': 'ParcelDo',
    'milesaway': 'MilesAway',
    'dvcexpress': 'DvcExpress',
    'amaze': 'Amaze',
    'amaze_docs': 'Amaze Docs',
    'udaan': 'Udaan Express',
    'udaan_b2b': 'Udaan Express',
    'ecommexpress_premium': 'Ecom Express',
    'delhivery_20kg': 'Delhivery',
    'delhivery_20kg_mps': 'Delhivery',
    'tci_express': 'Tci Express',
    'pidge': 'Pidge',
    'delhivery_docs': 'Delhivery',
    'xpressbees_air': 'Xpressbees',
    'xpressbees_otp': 'Xpressbees',
    'xpressbees_docs': 'Xpressbees'
}

module.exports = {
    order
}