const BLUEDART_CODE_MAPPER_V2 = {
  "500-s": { scan_type: "OM", pickrr_sub_status_code: "" },
  "504-s": { scan_type: "OM", pickrr_sub_status_code: "" },
  "544-t": { scan_type: "OM", pickrr_sub_status_code: "" },
  "590-t": { scan_type: "OM", pickrr_sub_status_code: "" },
  "501-s": { scan_type: "OFP", pickrr_sub_status_code: "" },
  "016-s": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "017-s": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "500-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "501-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "502-s": { scan_type: "PPF", pickrr_sub_status_code: "CANC" },
  "502-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "503-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "504-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "505-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "506-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "508-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "509-t": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "510-t": { scan_type: "PPF", pickrr_sub_status_code: "REGU" },
  "511-t": { scan_type: "PPF", pickrr_sub_status_code: "NSL" },
  "512-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "513-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "514-t": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "531-t": { scan_type: "PPF", pickrr_sub_status_code: "SC" },
  "532-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "533-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "534-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "535-t": { scan_type: "PPF", pickrr_sub_status_code: "CANC" },
  "536-t": { scan_type: "PPF", pickrr_sub_status_code: "SC" },
  "537-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "540-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "541-t": { scan_type: "PPF", pickrr_sub_status_code: "NSL" },
  "542-t": { scan_type: "PPF", pickrr_sub_status_code: "SU" },
  "555-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "591-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "592-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "593-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "594-t": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "018-s": { scan_type: "PP", pickrr_sub_status_code: "" },
  "543-t": { scan_type: "PPF", pickrr_sub_status_code: "HO" },
  "015-s": { scan_type: "PP", pickrr_sub_status_code: "" },
  "538-t": { scan_type: "SHP", pickrr_sub_status_code: "" },
  "001-s": { scan_type: "SHP", pickrr_sub_status_code: "" },
  "002-s": { scan_type: "OO", pickrr_sub_status_code: "" },
  "007-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "021-s": { scan_type: "OT", pickrr_sub_status_code: "" },
  "032-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "037-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "048-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "049-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "058-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "068-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "106-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "107-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "143-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "154-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "065-t": { scan_type: "OT", pickrr_sub_status_code: "" },
  "001-rs": { scan_type: "OT", pickrr_sub_status_code: "" },
  "007-rs": { scan_type: "OT", pickrr_sub_status_code: "" },
  "007-rt": { scan_type: "OT", pickrr_sub_status_code: "" },
  "020-rs": { scan_type: "OT", pickrr_sub_status_code: "" },
  "021-rs": { scan_type: "OT", pickrr_sub_status_code: "" },
  "313-rt": { scan_type: "OT", pickrr_sub_status_code: "" },
  "027-rs": { scan_type: "OT", pickrr_sub_status_code: "" },
  "222-t": { scan_type: "RAD", pickrr_sub_status_code: "" },
  "002-rs": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "001-t": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "002-t": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "003-t": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "008-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "009-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "010-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "011-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "012-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "013-t": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "014-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "017-t": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "019-t": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "020-t": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "029-t": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "029-s": { scan_type: "UD", pickrr_sub_status_code: "CR-OTP" },
  "044-t": { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  "062-t": { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  "066-t": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "076-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "137-t": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "139-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "175-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "201-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "202-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "203-t": { scan_type: "UD", pickrr_sub_status_code: "OPDEL" },
  "204-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "205-t": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "208-t": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "217-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "218-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "777-t": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "120-t": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "056-t": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "000-t": { scan_type: "DL", pickrr_sub_status_code: "" },
  "021-t": { scan_type: "LT", pickrr_sub_status_code: "" },
  "025-t": { scan_type: "DM", pickrr_sub_status_code: "" },
  "129-t": { scan_type: "DM", pickrr_sub_status_code: "" },
  "130-t": { scan_type: "DM", pickrr_sub_status_code: "" },
  "186-t": { scan_type: "LT", pickrr_sub_status_code: "" },
  "070-t": { scan_type: "LT", pickrr_sub_status_code: "" },
  "021-rt": { scan_type: "LT", pickrr_sub_status_code: "" },
  "025-rt": { scan_type: "DM", pickrr_sub_status_code: "" },
  "016-t": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "104-t": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "123-t": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "074-rt": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "123-rt": { scan_type: "RTO", pickrr_sub_status_code: "" },

  // "503-s": { scan_type: "UD", pickrr_sub_status_code: "OTH" },

  "034-t": { scan_type: "RTO-OT", pickrr_sub_status_code: "" },
  "019-s": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "035-rt": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "219-rt": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "001-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "002-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "003-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "004-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "005-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "008-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "009-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "010-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "011-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "012-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "013-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "014-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "017-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "019-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "020-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "201-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "202-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "203-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "204-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "205-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "218-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "777-rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "qc -rt": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "188-t": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "105-t": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "000-rt": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "188-rt": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "105-rt": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "098-rt": { scan_type: "OC", pickrr_sub_status_code: "" },
  "020-s": { scan_type: "OT", pickrr_sub_status_code: "" },
  "003-s": { scan_type: "OT", pickrr_sub_status_code: "" },
};

const PUSH_PARTITION_COUNT = 10;
const PUSH_GROUP_NAME = "bluedart-push-group";
const PUSH_TOPIC_NAME = "bluedart_push";
module.exports = {
  BLUEDART_CODE_MAPPER_V2,
  PUSH_PARTITION_COUNT,
  PUSH_GROUP_NAME,
  PUSH_TOPIC_NAME,
};
