const BLUEDART_CODE_MAPPER_V2 = {
  "500-S": { scan_type: "OM", pickrr_sub_status_code: "" },
  "504-S": { scan_type: "OM", pickrr_sub_status_code: "" },
  "544-T": { scan_type: "OM", pickrr_sub_status_code: "" },
  "590-T": { scan_type: "OM", pickrr_sub_status_code: "" },
  "501-S": { scan_type: "OFP", pickrr_sub_status_code: "" },
  "016-S": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "017-S": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "500-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "501-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "502-S": { scan_type: "PPF", pickrr_sub_status_code: "CANC" },
  "502-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "503-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "504-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "505-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "506-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "508-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "509-T": { scan_type: "PPF", pickrr_sub_status_code: "REJ" },
  "510-T": { scan_type: "PPF", pickrr_sub_status_code: "REGU" },
  "511-T": { scan_type: "PPF", pickrr_sub_status_code: "NSL" },
  "512-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "513-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "514-T": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "531-T": { scan_type: "PPF", pickrr_sub_status_code: "SC" },
  "532-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "533-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "534-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "535-T": { scan_type: "PPF", pickrr_sub_status_code: "CANC" },
  "536-T": { scan_type: "PPF", pickrr_sub_status_code: "SC" },
  "537-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "540-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "541-T": { scan_type: "PPF", pickrr_sub_status_code: "NSL" },
  "542-T": { scan_type: "PPF", pickrr_sub_status_code: "SU" },
  "555-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "591-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "592-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "593-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "594-T": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "018-S": { scan_type: "PP", pickrr_sub_status_code: "" },
  "543-T": { scan_type: "PP", pickrr_sub_status_code: "" },
  "015-S": { scan_type: "PP", pickrr_sub_status_code: "" },
  "538-T": { scan_type: "SHP", pickrr_sub_status_code: "" },
  "001-S": { scan_type: "SHP", pickrr_sub_status_code: "" },
  "002-S": { scan_type: "OT", pickrr_sub_status_code: "" },
  "007-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "021-S": { scan_type: "OT", pickrr_sub_status_code: "" },
  "032-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "037-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "048-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "049-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "058-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "068-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "106-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "107-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "143-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "154-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "065-T": { scan_type: "OT", pickrr_sub_status_code: "" },
  "001-RS": { scan_type: "OT", pickrr_sub_status_code: "" },
  "007-RS": { scan_type: "OT", pickrr_sub_status_code: "" },
  "007-RT": { scan_type: "OT", pickrr_sub_status_code: "" },
  "020-RS": { scan_type: "OT", pickrr_sub_status_code: "" },
  "021-RS": { scan_type: "OT", pickrr_sub_status_code: "" },
  "313-RT": { scan_type: "OT", pickrr_sub_status_code: "" },
  "027-RS": { scan_type: "OT", pickrr_sub_status_code: "" },
  "222-T": { scan_type: "RAD", pickrr_sub_status_code: "" },
  "002-RS": { scan_type: "OO", pickrr_sub_status_code: "" },
  "001-T": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "002-T": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "003-T": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "008-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "009-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "010-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "011-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "012-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "013-T": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "014-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "017-T": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "019-T": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "020-T": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "029-T": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "029-S": { scan_type: "UD", pickrr_sub_status_code: "CR-OTP" },
  "044-T": { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  "062-T": { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  "066-T": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "076-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "137-T": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "139-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "175-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "201-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "202-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "203-T": { scan_type: "UD", pickrr_sub_status_code: "OPDEL" },
  "204-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "205-T": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "208-T": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "217-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "218-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "777-T": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "120-T": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "056-T": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "000-T": { scan_type: "DL", pickrr_sub_status_code: "" },
  "021-T": { scan_type: "LT", pickrr_sub_status_code: "" },
  "025-T": { scan_type: "DM", pickrr_sub_status_code: "" },
  "129-T": { scan_type: "DM", pickrr_sub_status_code: "" },
  "130-T": { scan_type: "DM", pickrr_sub_status_code: "" },
  "186-T": { scan_type: "LT", pickrr_sub_status_code: "" },
  "070-T": { scan_type: "LT", pickrr_sub_status_code: "" },
  "021-RT": { scan_type: "LT", pickrr_sub_status_code: "" },
  "025-RT": { scan_type: "DM", pickrr_sub_status_code: "" },
  "016-T": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "104-T": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "123-T": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "074-RT": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "123-RT": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "503-S": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "034-T": { scan_type: "RTO-OT", pickrr_sub_status_code: "" },
  "019-S": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "035-RT": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "219-RT": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "001-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "002-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "003-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "004-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "005-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "008-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "009-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "010-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "011-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "012-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "013-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "014-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "017-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "019-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "020-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "201-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "202-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "203-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "204-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "205-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "218-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "777-RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "QC -RT": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "188-T": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "105-T": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "000-RT": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "188-RT": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "105-RT": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "098-RT": { scan_type: "OC", pickrr_sub_status_code: "" },
};

module.exports = {
  BLUEDART_CODE_MAPPER_V2,
};
