const PULL_TOPIC_NAME = "tci_pull";
const PULL_GROUP_NAME = "tci-pull-group";
const PULL_PARTITION_COUNT = 10;
const PULL_MAPPER = {
  PKP: { scan_type: "PP", pickrr_sub_status_code: "" },
  DIS: { scan_type: "SHP", pickrr_sub_status_code: "" },
  ARR: { scan_type: "RAD", pickrr_sub_status_code: "" },
  OFD: { scan_type: "OO", pickrr_sub_status_code: "" },
  D00: { scan_type: "DL", pickrr_sub_status_code: "" },
  D01: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D02: { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  D03: { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  D04: { scan_type: "UD", pickrr_sub_status_code: "AI" },
  D05: { scan_type: "UD", pickrr_sub_status_code: "CR" },
  D06: { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  D07: { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  D08: { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  D09: { scan_type: "OT", pickrr_sub_status_code: "" },
  D10: { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  D11: { scan_type: "OT", pickrr_sub_status_code: "" },
  D12: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D13: { scan_type: "OT", pickrr_sub_status_code: "" },
  D14: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D15: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D16: { scan_type: "UD", pickrr_sub_status_code: "AI" },
  D17: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D18: { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  D19: { scan_type: "UD", pickrr_sub_status_code: "SD" },
  D20: { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  D21: { scan_type: "OT", pickrr_sub_status_code: "" },
  D22: { scan_type: "OT", pickrr_sub_status_code: "" },
  D23: { scan_type: "RTO", pickrr_sub_status_code: "" },
  D26: { scan_type: "LT", pickrr_sub_status_code: "" },
  D27: { scan_type: "OT", pickrr_sub_status_code: "" },
  D29: { scan_type: "UD", pickrr_sub_status_code: "AI" },
  D30: { scan_type: "UD", pickrr_sub_status_code: "REST" },
  D31: { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  D32: { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  D33: { scan_type: "OT", pickrr_sub_status_code: "" },
  D34: { scan_type: "UD", pickrr_sub_status_code: "AI" },
  D35: { scan_type: "OT", pickrr_sub_status_code: "" },
  D36: { scan_type: "OT", pickrr_sub_status_code: "" },
  D37: { scan_type: "DM", pickrr_sub_status_code: "" },
  D38: { scan_type: "OT", pickrr_sub_status_code: "" },
  D39: { scan_type: "UD", pickrr_sub_status_code: "CD" },
  D43: { scan_type: "DM", pickrr_sub_status_code: "" },
  D44: { scan_type: "OT", pickrr_sub_status_code: "" },
  D50: { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  D51: { scan_type: "OT", pickrr_sub_status_code: "" },
  D52: { scan_type: "OT", pickrr_sub_status_code: "" },
  D53: { scan_type: "OT", pickrr_sub_status_code: "" },
  D54: { scan_type: "OT", pickrr_sub_status_code: "" },
  D55: { scan_type: "OT", pickrr_sub_status_code: "" },
  D56: { scan_type: "OT", pickrr_sub_status_code: "" },
  D57: { scan_type: "OT", pickrr_sub_status_code: "" },
  D58: { scan_type: "OT", pickrr_sub_status_code: "" },
  D59: { scan_type: "OT", pickrr_sub_status_code: "" },
  D60: { scan_type: "OT", pickrr_sub_status_code: "" },
  D61: { scan_type: "OC", pickrr_sub_status_code: "" },
  D62: { scan_type: "OT", pickrr_sub_status_code: "" },
  D63: { scan_type: "OT", pickrr_sub_status_code: "" },
  D64: { scan_type: "OT", pickrr_sub_status_code: "" },
  D68: { scan_type: "OT", pickrr_sub_status_code: "" },
  D69: { scan_type: "OT", pickrr_sub_status_code: "" },
  D77: { scan_type: "UD", pickrr_sub_status_code: "OPDEL" },
  D78: { scan_type: "UD", pickrr_sub_status_code: "REST" },
  D80: { scan_type: "OT", pickrr_sub_status_code: "" },
  D81: { scan_type: "OT", pickrr_sub_status_code: "" },
  D83: { scan_type: "DL", pickrr_sub_status_code: "" },
  D84: { scan_type: "OT", pickrr_sub_status_code: "" },
  D85: { scan_type: "UD", pickrr_sub_status_code: "CD" },
  D86: { scan_type: "UD", pickrr_sub_status_code: "OTH" },
};

module.exports = {
  PULL_GROUP_NAME,
  PULL_TOPIC_NAME,
  PULL_MAPPER,
  PULL_PARTITION_COUNT,
};
