const XBS_STATUS_MAPPER = {
  "Data Received-DRC": { scan_type: "OP", pickrr_sub_status_code: "" },
  "Pickup Created-PUC": { scan_type: "OM", pickrr_sub_status_code: "" },
  "Out for Pickup-OFP": { scan_type: "OFP", pickrr_sub_status_code: "" },
  "PickDone-PUD": { scan_type: "PP", pickrr_sub_status_code: "" },
  "6-PND": { scan_type: "PPF", pickrr_sub_status_code: "CANC" },
  "9-PND": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "0-PND": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "7-PND": { scan_type: "PPF", pickrr_sub_status_code: "AI" },
  "3-PND": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "13-PND": { scan_type: "PPF", pickrr_sub_status_code: "HO" },
  "14-PND": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "10-PND": { scan_type: "PPF", pickrr_sub_status_code: "SU" },
  "18-PND": { scan_type: "PPF", pickrr_sub_status_code: "AI" },
  "1-PND": { scan_type: "PPF", pickrr_sub_status_code: "SNR" },
  "8-PND": { scan_type: "PPF", pickrr_sub_status_code: "SU" },
  "12-PND": { scan_type: "PPF", pickrr_sub_status_code: "SC" },
  "4-PND": { scan_type: "PPF", pickrr_sub_status_code: "NA" },
  "Picked-PKD": { scan_type: "SHP", pickrr_sub_status_code: "" },
  "In Transit-IT": { scan_type: "OT", pickrr_sub_status_code: "" },
  "Reached at Destination-RAD": { scan_type: "RAD", pickrr_sub_status_code: "" },
  "Out for Delivery-OFD": { scan_type: "OO", pickrr_sub_status_code: "" },
  "2-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "3-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "4-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "6-UD": { scan_type: "UD", pickrr_sub_status_code: "CNR" },
  "8-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "9-UD": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "14-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "17-UD": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "18-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "19-UD": { scan_type: "UD", pickrr_sub_status_code: "OPDEL" },
  "24-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "25-UD": { scan_type: "UD", pickrr_sub_status_code: "CI" },
  "27-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "29-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "30-UD": { scan_type: "UD", pickrr_sub_status_code: "REST" },
  "31-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "32-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "37-UD": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "68-UD": { scan_type: "UD", pickrr_sub_status_code: "ODA" },
  "69-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "70-UD": { scan_type: "UD", pickrr_sub_status_code: "CR" },
  "72-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "111-UD": { scan_type: "UD", pickrr_sub_status_code: "CR-OTP" },
  "Delivered-DLVD": { scan_type: "DL", pickrr_sub_status_code: "" },
  "Lost-LOST": { scan_type: "LT", pickrr_sub_status_code: "" },
  "RTO Notified-RTON": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "Return to Origin-RTO": { scan_type: "RTO", pickrr_sub_status_code: "" },
  "RTO In Transit-RTO-IT": { scan_type: "RTO-OT", pickrr_sub_status_code: "" },
  "Reached at Origin-RAO": { scan_type: "RTO-OT", pickrr_sub_status_code: "" },
  "RTO Out for Delivery-RTO-OFD": { scan_type: "RTO-OO", pickrr_sub_status_code: "" },
  "RTO Delivered-RTD": { scan_type: "RTD", pickrr_sub_status_code: "" },
  "RTO Undelivered-RTU": { scan_type: "RTO UD", pickrr_sub_status_code: "" },
  "ShipmentTransit damage-STD": { scan_type: "DM", pickrr_sub_status_code: "" },
  "Shortage-STG": { scan_type: "LT", pickrr_sub_status_code: "" },
  "Return To Origin Shortage-RTO-STG": { scan_type: "LT", pickrr_sub_status_code: "" },
  "Pickup Not Done-PND": { scan_type: "PPF", pickrr_sub_status_code: "" },
  "22-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "39-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "77-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "78-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "79-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "80-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "81-UD": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "82-UD": { scan_type: "UD", pickrr_sub_status_code: "CD" },
  "83-UD": { scan_type: "UD", pickrr_sub_status_code: "CI" },
  "84-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "86-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "87-UD": { scan_type: "UD", pickrr_sub_status_code: "REST" },
  "90-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "91-UD": { scan_type: "UD", pickrr_sub_status_code: "CNA" },
  "92-UD": { scan_type: "UD", pickrr_sub_status_code: "REST" },
  "94-UD": { scan_type: "UD", pickrr_sub_status_code: "AI" },
  "1001-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "1000-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "85-UD": { scan_type: "UD", pickrr_sub_status_code: "SD" },
  "93-UD": { scan_type: "UD", pickrr_sub_status_code: "REST" },
  "88-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "89-UD": { scan_type: "UD", pickrr_sub_status_code: "OTH" },
  "InTransit-IT": { scan_type: "OT", pickrr_sub_status_code: "" },
};

const XBS_TOPICS_COUNT = 2;

module.exports = {
  XBS_STATUS_MAPPER,
  XBS_TOPICS_COUNT,
};
